{{- range $name, $svc := .Values.services }}
{{- if and $svc.serviceAccount $svc.serviceAccount.annotations }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    chart: {{ $.Chart.Name }}
  annotations:
    {{- toYaml $svc.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
