apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: koomi1/retail-app-orders:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RETAIL_ORDERS_PERSISTENCE_PROVIDER
              value: "in-memory"
            - name: RETAIL_ORDERS_MESSAGING_PROVIDER
              value: "in-memory"
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
